# Stage 1: build the image
FROM node:20-alpine AS build

WORKDIR /app

COPY ./package*.json ./

RUN npm install --legacy-peer-deps

COPY ./ ./

RUN npm run build

# Stage 2: serve the application using Nginx Web Server
FROM nginx:alpine

COPY --from=build /app/dist/pokemon-angular/browser /usr/share/nginx/html
# COPY ci/mime.types /etc/nginx/mime.types
COPY ci/nginx.conf /etc/nginx/nginx.conf

EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]
