# Stage 1: build the image
FROM node:20-alpine AS build

WORKDIR /app

COPY ./package*.json ./

RUN npm install --legacy-peer-deps

COPY ./ ./

# Make Environment for test and check code
# # Install Chromium and dependencies
# RUN apk update && \
#     apk add --no-cache \
#     chromium \
#     chromium-chromedriver \
#     wget \
#     gnupg \
#     curl \
#     # Ensure that the chromium binary path is available
#     && ln -s /usr/bin/chromium-browser /usr/bin/google-chrome

# # Set environment variables for Chromium
# ENV CHROME_BIN=/usr/bin/chromium-browser

# # Check code
# RUN npm test

RUN npm run build

# Stage 2: serve the application using Nginx Web Server
FROM nginx:alpine

COPY --from=build /app/dist/pokemon-angular/browser /usr/share/nginx/html
COPY ./ci/nginx.conf /etc/nginx/nginx.conf

EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]
