name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-monolith:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -f ci/Dockerfile -t pokemon-angular .

    - name: Check Docker Image
      run: |
        docker images

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker Image
      run: |
        docker tag pokemon-angular ${{ secrets.DOCKER_USERNAME }}/pokemon-angular:latest

    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/pokemon-angular:latest

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-southeast-1' # Change this to your region

    - name: Decode SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_DNS }} >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

    - name: Upload files to EC2 instance
      run: |
        mkdir -p /home/${{ secrets.EC2_USER }}/app
        scp -i ~/.ssh/ec2_key.pem -r . ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_DNS }}:/home/${{ secrets.EC2_USER }}/app
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

    # - name: Set up SSH key
    #   run: |
    #     echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ec2_key.pem
    #     chmod 400 ec2_key.pem

    # - name: Upload Files to EC2
    #   run: |
    #     scp -i "ec2_key.pem" -r . ec2-user@${{ secrets.EC2_PUBLIC_DNS }}:/home/ec2-user/app
    #   shell: /usr/bin/bash -e {0}
    #   env:
    #     AWS_DEFAULT_REGION: ap-southeast-1
    #     AWS_REGION: ap-southeast-1
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # - name: Clean up SSH key
    #   run: |
    #     rm -f ec2_key.pem

    - name: Deploy to EC2 and Run Docker Compose
      run: |
        mkdir -p /home/${{ secrets.EC2_USER }}/app
        # SSH into EC2 instance and run Docker Compose commands
        ssh -i "${{ secrets.EC2_SSH_KEY }}" ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
          cd /home/${{ secrets.EC2_USER }}/app
          docker-compose pull
          docker-compose up -d
        EOF
